### ISSUE TITLE
Scroll to top of Label Next when a new model becomes available

### ISSUE THREAD

**Issue by keithcallenberg** [label-sleuth/label-sleuth#241] opened 2022-09-22 15:00 UTC
**Is your feature request related to a problem?**
When I am labeling in the Label Next panel and a new model becomes available, the elements are automatically reloaded and so the element I was on is no longer available. That is fine, but now I am at some arbitrary place in the list. Maybe the element ordering is arbitrary, but I always find myself manually scrolling back up to the top when this happens.

**What is the expected behavior?**
When a new model is loaded, the Label Next panel should scroll up to the top.

**Additional context (if any):**
N/A

**Comment by martinscooper** [comment] 2022-09-26 19:25
Hi @keithcallenberg, thanks for creating this issue. 

I can't work on this right now but I will describe how this could be implemented. Writing out loud, the required changes would be the following:
- A custom hook similar to [useScrollMainPanelElementIntoView](https://github.com/label-sleuth/label-sleuth/blob/main/frontend/src/modules/Workplace/sidebar/customHooks/useScrollElementIntoView.js) should be implemented. Other option is to implement this in the same custom hook, and change its name to `useScrollElementIntoView`. 
- A `useEffect` has to be added that is run when the `modelVersion` changes. When it changes, the `id` of the first element of the `Label next` panel has to be retrieved and scrolled into view. This `id` can be accesed doing:
`const labelNextElements = useSelector(state => state.workspace.panels[panelIds.LABEL_NEXT].elements)` and then `const firstElementId = Object.values(labelNextElements)[0].id`. Finally, the DOM element has to be retrieved and then passed to the `scrollIntoElementView()` function.

I am setting this as a Good first issue.

**Comment by martinscooper** [comment] 2022-10-18 11:32
This issue seems to be solved because of the pagination changes. @keithcallenberg could you check if you are still being able to reproduce it?

**Comment by martinscooper** [comment] 2022-11-01 13:09
I couldn't reproduce this issue againg after pagination was added. Closing this issue.

**Closed by martinscooper** 2022-11-01 13:09 UTC
Labels: enhancement
